version: 2
jobs:
  build:
    working_directory: /build
    docker:
      - image: openjdk:8u131
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ checksum "build.gradle" }}
      - run: bash gradlew check
      - save_cache:
          paths:
            - ~/.m2
          key: v1-{{ checksum "build.gradle" }}
      - store_test_results:
          path: /build/build/test-results
